/**
 * Demo REST API
 * User Management API.
 *
 * OpenAPI spec version: API v1.0.0
 * Contact: nhtoi@tma.com.vn
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AppUser } from './appUser';
import { AssetCategory } from './assetCategory';
import { AssetStatus } from './assetStatus';
import { AssetSupplier } from './assetSupplier';
import { Project } from './project';
import { Request } from './request';

export interface Asset { 
    appUser?: AppUser;
    assetCategory?: AssetCategory;
    assetStatus?: AssetStatus;
    assetSupplier?: AssetSupplier;
    comments?: string;
    id?: number;
    imei?: string;
    inventoryNumber?: string;
    modified?: Date;
    name?: string;
    ownership?: string;
    project?: Project;
    requests?: Array<Request>;
    serialNumber?: string;
}