/**
 * Demo REST API
 * User Management API.
 *
 * OpenAPI spec version: API v1.0.0
 * Contact: nhtoi@tma.com.vn
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface AssetCreateDto { 
    categoryId?: number;
    comments?: string;
    imei?: string;
    inventoryNumber?: string;
    name?: string;
    ownership?: string;
    projectId?: number;
    serialNumber?: string;
    statusId?: number;
    supplierId?: number;
    userId?: number;
}