/**
 * Demo REST API
 * User Management API.
 *
 * OpenAPI spec version: API v1.0.0
 * Contact: nhtoi@tma.com.vn
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AppUser } from './appUser';
import { Asset } from './asset';

export interface Request { 
    assets?: Asset;
    id?: number;
    reason?: string;
    requestType?: string;
    status?: string;
    updateAt?: Date;
    userApprove?: Array<AppUser>;
    userReceive?: Array<AppUser>;
    userSend?: Array<AppUser>;
}